# Generated by Django 5.0 on 2023-12-22 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='enter',
        ),
    ]
