# Generated by Django 5.0 on 2023-12-23 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_slider_u_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='name',
            new_name='sub_title',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='sub_name',
            new_name='title',
        ),
    ]
