# Generated by Django 5.0 on 2023-12-25 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_rename_sub_title_slider_sub_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='u_id',
        ),
    ]
