# Generated by Django 5.0 on 2023-12-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_maincatagory'),
    ]

    operations = [
        migrations.CreateModel(
            name='subcatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.BigIntegerField()),
                ('image', models.FileField(default='', upload_to='media/')),
            ],
        ),
    ]
