# Generated by Django 5.0 on 2023-12-27 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_subcatagory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcatagory',
            name='price',
        ),
    ]
