# Generated by Django 5.0 on 2023-12-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_remove_subcatagory_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcatagory',
            name='sub_n',
            field=models.CharField(default='', max_length=100),
        ),
    ]
