# Generated by Django 5.0 on 2023-12-27 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_subcatagory_sub_n'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcatagory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='subcatagory',
            name='sub_n',
        ),
    ]
