# Generated by Django 5.0 on 2023-12-27 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_remove_subcatagory_image_remove_subcatagory_sub_n'),
    ]

    operations = [
        migrations.CreateModel(
            name='petacatgory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('image', models.FileField(default='', upload_to='media/')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.subcatagory')),
            ],
        ),
    ]
