# Generated by Django 5.0 on 2023-12-28 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_petacatgory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petacatgory',
            name='description',
        ),
    ]
