# Generated by Django 5.0 on 2023-12-30 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_remove_petacatgory_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('qty', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=500)),
                ('amount', models.IntegerField(max_length=500)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.petacatgory')),
            ],
        ),
    ]
