# Generated by Django 5.0 on 2023-12-31 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_remove_cart_product_id_remove_cart_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
